$(document).ready(function(){
	$(".hid").hide();
$("#but1").click(function(){
	$("#1").fadeToggle(500);
	});
	$("#but2").click(function(){
	$("#2").fadeToggle(500);
	});
	$("#but3").click(function(){
	$("#3").fadeToggle(500);
	});
	$("#but4").click(function(){
	$("#4").fadeToggle(500);
	});
	$("#but5").click(function(){
	$("#5").fadeToggle(500);
	});
	$("#addreply1").click(function(){
		$("#ar1").fadeToggle(500);
	});
	$("#addreply2").click(function(){
		$("#ar2").fadeToggle(500);
	});
	$("#addreply3").click(function(){
		$("#ar3").fadeToggle(500);
	});
	$("#addreply4").click(function(){
		$("#ar4").fadeToggle(500);
	});
	$("#addreply5").click(function(){
		$("#ar5").fadeToggle(500);
	});
	$("#sub1").click(function(){
		$("#ar1").slideUp(500);
		});
		$("#sub2").click(function(){
		$("#ar2").slideUp(500);
		});
		$("#sub3").click(function(){
		$("#ar3").slideUp(500);
		});
		$("#sub4").click(function(){
		$("#ar4").slideUp(500);
		});
		$("#sub5").click(function(){
		$("#ar5").slideUp(500);
		});
});
